version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
      # 🔥 AQUÍ CARGAS TU BACKUP LOCAL
      # Se ejecutará automáticamente al crear el contenedor por primera vez
      - ./backup.sql:/container-entrypoint-initdb.d/setup.sql 

  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    depends_on:
      - oracle
    environment:
      DB_HOST: oracle
      DB_PORT: 1521
      DB_USER: system
      DB_PASSWORD: oracle
      DB_NAME: XE
    networks:
      - default

  frontend:
    build: ./frontend-angular
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - default

volumes:
  oracle-data: