-- INSERT INTO TIPO_CELDA (NOMBRE)
--VALUES ('MOTO');

-- Select * from TIPO_CELDA;

INSERT INTO SENSOR (DESCRIPCION) VALUES ('Sensor_001');
INSERT INTO SENSOR (DESCRIPCION) VALUES ('Sensor_002');
INSERT INTO SENSOR (DESCRIPCION) VALUES ('Sensor_003');
INSERT INTO SENSOR (DESCRIPCION) VALUES ('Sensor_004');
INSERT INTO SENSOR (DESCRIPCION) VALUES ('Sensor_005');

INSERT INTO CELDA (ID_PARQUEADERO, ID_TIPO_CELDA, ID_SENSOR, ESTADO, ULTIMO_CAMBIO_ESTADO)
VALUES (1, 1, 1, 'LIBRE', CURRENT_TIMESTAMP);

INSERT INTO CELDA (ID_PARQUEADERO, ID_TIPO_CELDA, ID_SENSOR, ESTADO, ULTIMO_CAMBIO_ESTADO)
VALUES (1, 1, 2, 'LIBRE', CURRENT_TIMESTAMP);

INSERT INTO CELDA (ID_PARQUEADERO, ID_TIPO_CELDA, ID_SENSOR, ESTADO, ULTIMO_CAMBIO_ESTADO)
VALUES (1, 1, 3, 'LIBRE', CURRENT_TIMESTAMP);

INSERT INTO CELDA (ID_PARQUEADERO, ID_TIPO_CELDA, ID_SENSOR, ESTADO, ULTIMO_CAMBIO_ESTADO)
VALUES (1, 1, 4, 'LIBRE', CURRENT_TIMESTAMP);

INSERT INTO CELDA (ID_PARQUEADERO, ID_TIPO_CELDA, ID_SENSOR, ESTADO, ULTIMO_CAMBIO_ESTADO)
VALUES (1, 1, 5, 'LIBRE', CURRENT_TIMESTAMP);

SELECT * FROM TIPO_VEHICULO;

INSERT INTO METODO_PAGO (NOMBRE) VALUES ('EFECTIVO');
INSERT INTO METODO_PAGO (NOMBRE) VALUES ('TARJETA');
INSERT INTO METODO_PAGO (NOMBRE) VALUES ('TRANSFERENCIA');

INSERT INTO TIPO_VEHICULO (NOMBRE) VALUES ('AUTOMOVIL');
INSERT INTO TIPO_VEHICULO (NOMBRE) VALUES ('MOTOCICLETA');

