pipeline {
    agent any

    tools {
        nodejs 'NodeJS-24'  // ¿Tu local usa Node 18 o 20+?
    }

    environment {
        SONAR_HOME = tool 'SonarQube' // nombre configurado en Jenkins
        CHROME_BIN = "/usr/bin/chromium"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                dir('frontend-angular') {
                    sh 'npm install'
                }
            }
        }

        stage('Run tests with coverage') {
            steps {
                dir('frontend-angular') {
                    sh 'npm run test:ci'
                }
            }
        }

        stage('SonarQube analysis') {
            steps {
                dir('frontend-angular') {
                    withSonarQubeEnv('SonarQube') { // nombre en Jenkins
                        sh "${SONAR_HOME}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}