pipeline {
    agent {
        docker {
            image 'cypress/browsers:node18.12.0-chrome107'
            args '--user=root'
        }
    }

    environment {
        SONARQUBE_ENV = 'SonarQube'
        CHROME_BIN = '/usr/bin/google-chrome'
    }

    stages {

        stage('Install') {
            steps {
                dir('frontend-angular') {
                    sh 'npm ci'
                }
            }
        }

        stage('Test CI') {
            steps {
                dir('frontend-angular') {
                    sh 'npm run test:ci'
                }
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('frontend-angular') {
                    withSonarQubeEnv("${SONARQUBE_ENV}") {
                        sh 'npx sonar-scanner'
                    }
                }
            }
        }
    }
}